name: lomax
favicon: null
layout_spectrum: 0.1672239163890481
typography_spectrum: 0.02853811695240438
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#002835'
    - '#79a8d1'
    - '#b3d0e3'
    - '#ffa468'
    - '#24688a'
  brandStrength: 0.8125
  lightness: 0.625
  saturation: 0.75
  rhythmicContrast: 0.75
purpose: []
