name: lomax
favicon: null
layout_spectrum: 0.1672239163890481
typography_spectrum: 0.02853811695240438
title: Lomax Land
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#191d45'
    - '#ecffff'
    - '#515289'
    - '#838e4c'
    - '#d2b7af'
  brandStrength: 0.8125
  lightness: 0.625
  saturation: 0.75
  rhythmicContrast: 0.75
purpose: []
